### ISSUE TITLE
ModuleNotFoundError: No module named 'data.dna_rendering'

### ISSUE THREAD

**Issue by WangPu1999** [3DHumanRehab/SemanticGraph-Gaussian#1]
Thanks for your amazing work!

I met a problem when I try 'bash train_zju_mocap_refine.sh'
```
(hugs) wangpu@ubuntu:/mnt/sda/wangpu/projects/SemanticGraph-Gaussian$ bash train_zju_mocap_refine.sh
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from scene.dataset_readers import fetchPly
  File "/mnt/sda/wangpu/projects/SemanticGraph-Gaussian/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/mnt/sda/wangpu/projects/SemanticGraph-Gaussian/scene/dataset_readers.py", line 33, in <module>
    from data.dna_rendering.dna_rendering_sample_code.SMCReader import SMCReader
ModuleNotFoundError: No module named 'data.dna_rendering'
```
I have tried 'pip install data' and 'pip install data.dna_rendering', but it does not work. How can i solove it?

Moreover, there is a little mistake in your 'Generate SMPL model with semantic labels' part of README.md(but it does not matter)

Thanks for your amazing work again and thank you for reading my issue!

**Comment by soslsos16** [comment]
I encountered the same issue too. Have you resolved it now?

**Comment by WangPu1999** [comment]
> I encountered the same issue too. Have you resolved it now?

no🥲

**Comment by soslsos16** [comment]
> > 我也遇到了同样的问题。您现在解决了吗？
> 
> 不🥲

I solve this problem ,you can copy this folder from other project such as MOSS ,it can work .

**Comment by WangPu1999** [comment]
> > > 我也遇到了同样的问题。您现在解决了吗？
> > 
> > 
> > 不🥲
> 
> I solve this problem ,you can copy this folder from other project such as MOSS ,it can work .

thank you!
i have solved this problem too by copying the smcreader.py from the dna_rendering code .
